### ISSUE TITLE
Silent Running Without Dumping Debug Info

### ISSUE THREAD

**Issue by ronxin** [mattburg/EdgeBoost#2]
Would you consider toggling the following lines to support silent running?

https://github.com/mattburg/EdgeBoost/blob/master/edgeboost/Community.py#L59
https://github.com/mattburg/EdgeBoost/blob/master/edgeboost/EdgeBoost.py#L40
https://github.com/mattburg/EdgeBoost/blob/master/edgeboost/EdgeBoost.py#L43
https://github.com/mattburg/EdgeBoost/blob/master/edgeboost/EdgeBoost.py#L46

**Comment by mattburg** [comment]
this is now fixed with the verbose argument
